version: '3.9'

services:
  web:
    container_name: speedsolverfrontend
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - 3001:80
    environment:
      - VITE_PORT=3000