"""empty message

Revision ID: 083c01a7b7d7
Revises: fb5b49f9bbe6
Create Date: 2025-05-24 19:46:52.027227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083c01a7b7d7'
down_revision: Union[str, None] = 'fb5b49f9bbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitations', sa.Column('invited_user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'organization_invitations', 'users', ['invited_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_invitations', type_='foreignkey')
    op.drop_column('organization_invitations', 'invited_user_id')
    # ### end Alembic commands ###
