"""empty message

Revision ID: 09ac58fca3de
Revises: d911c2926905
Create Date: 2025-04-19 19:16:11.073852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ac58fca3de'
down_revision: Union[str, None] = 'd911c2926905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_projects_teamId_fkey', 'team_projects', type_='foreignkey')
    op.drop_constraint('team_projects_projectId_fkey', 'team_projects', type_='foreignkey')
    op.create_foreign_key(None, 'team_projects', 'teams', ['teamId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_projects', 'projects', ['projectId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_projects', type_='foreignkey')
    op.drop_constraint(None, 'team_projects', type_='foreignkey')
    op.create_foreign_key('team_projects_projectId_fkey', 'team_projects', 'projects', ['projectId'], ['id'])
    op.create_foreign_key('team_projects_teamId_fkey', 'team_projects', 'teams', ['teamId'], ['id'])
    # ### end Alembic commands ###
