"""empty message

Revision ID: 1039991976d0
Revises: 502127285459
Create Date: 2025-05-13 16:17:48.737563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1039991976d0'
down_revision: Union[str, None] = '502127285459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_leaderId_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['leaderId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_leaderId_fkey', 'teams', 'users', ['leaderId'], ['id'])
    # ### end Alembic commands ###
