"""empty message

Revision ID: 238f6ee8f9e5
Revises: 09ac58fca3de
Create Date: 2025-04-20 13:36:42.374476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238f6ee8f9e5'
down_revision: Union[str, None] = '09ac58fca3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_invitations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_invitations', 'created_at')
    # ### end Alembic commands ###
