"""empty message

Revision ID: 36551275d3fe
Revises: e238014fade3
Create Date: 2025-04-19 18:37:47.025347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36551275d3fe'
down_revision: Union[str, None] = 'e238014fade3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'creator_id')
    # ### end Alembic commands ###
