"""empty message

Revision ID: 502127285459
Revises: 54cf0752aed6
Create Date: 2025-05-13 16:08:14.675114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502127285459'
down_revision: Union[str, None] = '54cf0752aed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_invitations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_invitations', 'created_at')
    # ### end Alembic commands ###
