"""empty message

Revision ID: 594cea1f36ec
Revises: 
Create Date: 2025-05-02 14:45:32.032876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '594cea1f36ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_team_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links_team_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['custom_team_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('objectives', sa.Column('responsible_person_id', sa.UUID(), nullable=True))
    op.drop_constraint('objectives_parent_objectiveId_fkey', 'objectives', type_='foreignkey')
    op.create_foreign_key(None, 'objectives', 'users', ['responsible_person_id'], ['id'])
    op.create_foreign_key(None, 'objectives', 'objectives', ['parent_objectiveId'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('team_invitations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('team_members', sa.Column('invited_by_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'team_members', 'team_invitations', ['invited_by_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('team_moderators', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('avatar_path', sa.String(), nullable=True))
    op.alter_column('users', 'registered',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'avatar_path')
    op.drop_column('teams', 'created_at')
    op.drop_column('team_moderators', 'created_at')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'invited_by_request_id')
    op.drop_column('team_invitations', 'created_at')
    op.drop_column('organizations', 'created_at')
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.create_foreign_key('objectives_parent_objectiveId_fkey', 'objectives', 'objectives', ['parent_objectiveId'], ['id'])
    op.drop_column('objectives', 'responsible_person_id')
    op.alter_column('email_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('links_team_roles')
    op.drop_table('custom_team_roles')
    # ### end Alembic commands ###
