"""empty message

Revision ID: 6452a4cc13cd
Revises: 26e74bb7d56d
Create Date: 2025-01-02 17:26:10.345848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6452a4cc13cd'
down_revision: Union[str, None] = '26e74bb7d56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verifications', 'created_at')
    # ### end Alembic commands ###
