"""empty message

Revision ID: 6643f9ccf5d9
Revises: c06adcf3e66f
Create Date: 2025-01-09 12:39:04.015173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6643f9ccf5d9'
down_revision: Union[str, None] = 'c06adcf3e66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('projectId')
    )
    op.add_column('team_projects', sa.Column('projectId', sa.UUID(), nullable=False))
    op.drop_constraint('team_projects_project_title_key', 'team_projects', type_='unique')
    op.create_foreign_key(None, 'team_projects', 'projects', ['projectId'], ['projectId'])
    op.drop_column('team_projects', 'project_description')
    op.drop_column('team_projects', 'project_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_projects', sa.Column('project_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('team_projects', sa.Column('project_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_projects', type_='foreignkey')
    op.create_unique_constraint('team_projects_project_title_key', 'team_projects', ['project_title'])
    op.drop_column('team_projects', 'projectId')
    op.drop_table('projects')
    # ### end Alembic commands ###
