"""empty message

Revision ID: 907e954e75a1
Revises: 1039991976d0
Create Date: 2025-05-13 16:18:26.391796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907e954e75a1'
down_revision: Union[str, None] = '1039991976d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objectives_responsible_person_id_fkey', 'objectives', type_='foreignkey')
    op.drop_constraint('objectives_author_id_fkey', 'objectives', type_='foreignkey')
    op.create_foreign_key(None, 'objectives', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'objectives', 'users', ['responsible_person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.create_foreign_key('objectives_author_id_fkey', 'objectives', 'users', ['author_id'], ['id'])
    op.create_foreign_key('objectives_responsible_person_id_fkey', 'objectives', 'users', ['responsible_person_id'], ['id'])
    # ### end Alembic commands ###
