"""empty message

Revision ID: 96db638aa74c
Revises: 6643f9ccf5d9
Create Date: 2025-01-09 12:41:37.424427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96db638aa74c'
down_revision: Union[str, None] = '6643f9ccf5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objectives', sa.Column('projectId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'objectives', 'projects', ['projectId'], ['projectId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.drop_column('objectives', 'projectId')
    # ### end Alembic commands ###
