"""empty message

Revision ID: a43295923d3c
Revises: 96db638aa74c
Create Date: 2025-01-14 15:03:18.857875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43295923d3c'
down_revision: Union[str, None] = '96db638aa74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objectives', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('objectives', sa.Column('deadline_date', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_profiles', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'about')
    op.drop_column('projects', 'created_at')
    op.drop_column('objectives', 'deadline_date')
    op.drop_column('objectives', 'created_at')
    # ### end Alembic commands ###
