"""empty message

Revision ID: ceb82bf36346
Revises: d4ace28995bb
Create Date: 2025-01-07 02:09:43.430747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb82bf36346'
down_revision: Union[str, None] = 'd4ace28995bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_verifications_userId_fkey', 'email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'email_verifications', 'users', ['userId'], ['userId'], ondelete='CASCADE')
    op.drop_constraint('user_profiles_userId_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['userId'], ['userId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_userId_fkey', 'user_profiles', 'users', ['userId'], ['userId'])
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.create_foreign_key('email_verifications_userId_fkey', 'email_verifications', 'users', ['userId'], ['userId'])
    # ### end Alembic commands ###
