"""empty message

Revision ID: e238014fade3
Revises: 29f26748a5e4
Create Date: 2025-04-19 17:36:01.775078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e238014fade3'
down_revision: Union[str, None] = '29f26748a5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_members_userId_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_moderators_userId_fkey', 'team_moderators', type_='foreignkey')
    op.create_foreign_key(None, 'team_moderators', 'users', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_moderators', type_='foreignkey')
    op.create_foreign_key('team_moderators_userId_fkey', 'team_moderators', 'users', ['userId'], ['id'])
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_userId_fkey', 'team_members', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
