"""empty message

Revision ID: e3eaf5e6dce6
Revises: 
Create Date: 2025-01-19 14:30:18.586496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3eaf5e6dce6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_moderators',
    sa.Column('projectModeratorId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('projectModeratorId')
    )
    op.add_column('objectives', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('objectives', sa.Column('deadline_date', sa.DateTime(), nullable=False))
    op.add_column('objectives', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'objectives', 'users', ['author_id'], ['userId'], ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'about')
    op.drop_constraint(None, 'objectives', type_='foreignkey')
    op.drop_column('objectives', 'author_id')
    op.drop_column('objectives', 'deadline_date')
    op.drop_column('objectives', 'created_at')
    op.drop_table('project_moderators')
    # ### end Alembic commands ###
