"""empty message

Revision ID: ef231739b375
Revises: a43295923d3c
Create Date: 2025-01-14 16:25:30.676196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef231739b375'
down_revision: Union[str, None] = 'a43295923d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_moderators',
    sa.Column('projectModeratorId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('projectModeratorId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_moderators')
    # ### end Alembic commands ###
