"""empty message

Revision ID: fb5b49f9bbe6
Revises: 
Create Date: 2025-05-24 19:45:01.118793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5b49f9bbe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('invited_by_leader_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_leader_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('join_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('links_team_roles', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'links_team_roles', 'custom_team_roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links_team_roles', type_='foreignkey')
    op.drop_column('links_team_roles', 'role_id')
    op.drop_table('organization_members')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
