version: '3.4'

services:
  speedsolverapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=5002
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ~/.aspnet/dev-certs/https:/home/app/.aspnet/https:ro