version: '3.4'

services:
  speedsolverapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./secrets:/home/app/.microsoft/usersecrets:ro
      - ./certs:/home/app/.aspnet/https:ro