version: '3.4'

services:
  speedsolverapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5005
      - ASPNETCORE_HTTPS_PORTS=5006
    ports:
      - "5005:5005"
      - "5006:5006"
    volumes:
      - ./secrets:/home/app/.microsoft/usersecrets:ro
      - ./certs:/home/app/.aspnet/https:ro