version: '3.4'

services:
  speedsolver.database:
    image: postgres:latest
    container_name: speedsolver.database
    environment:
        - POSTGRES_DB=speedsolver
        - POSTGRES_USER=speedsolver
        - POSTGRES_PASSWORD=555
    ports:
        - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
