name: Deployment

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master
      

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Downloading repository
        uses: actions/checkout@v4

      - name: Copy .env backend file
        run: |
          cd SpeedSolverBackend/SpeedSolverAPI
          echo "${{ secrets.ENV_SPEEDSOLVER }}" > .env

      - name: Copy .env frontend file
        run: |
          cd SpeedSolverFrontend
          echo "${{ secrets.ENV_SPEEDSOLVER_FRONTEND }}" > .env

      - name: Run Backend
        run: |
          make build-backend

      - name: Run Frontend
        run: |
          make build-frontend

      